<?php

namespace AppBundle\Repository;

/**
 * ContractorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractorsRepository extends \Doctrine\ORM\EntityRepository
{
}
