<?php

namespace AppBundle\Repository;

/**
 * ProductManufactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductManufactureRepository extends \Doctrine\ORM\EntityRepository
{
}
