<?php

namespace AppBundle\Repository;

/**
 * ProductColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductColorRepository extends \Doctrine\ORM\EntityRepository
{    
}
