<?php

namespace AppBundle\Repository;

/**
 * UnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
